### ISSUE TITLE
Getting below issue despite of using new token every time.

### ISSUE THREAD

**Issue by Bond-Prabal** [DanWahlin/acs-voice-calling-quickstart#2]
re:ACS:warning 3/12/2021, 12:38:4:998 [CallClient] [JS.TsCalling.MediaAgent] ffffffff: MA/webrtc2-4 On ICE candidate error turn::443?transport=tcp | 192.168.0.x:65281: code 401: Unauthorized
CallClient.e.warning.log @ sdk.bundle.js:149
debug @ debug.js:122
warn @ sdk.bundle.js:149
t.log @ sdk.bundle.js:131
(anonymous) @ sdk.bundle.js:36
t.log @ sdk.bundle.js:36
e.warn @ sdk.bundle.js:36
(anonymous) @ sdk.bundle.js:131
e._apply @ sdk.bundle.js:131
e.warn @ sdk.bundle.js:131
peerConnectionPromise.relayManagerProvider.getRelayManager.queryRelaysAsync.then.u.onicecandidateerror @ sdk.bundle.js:131

**Comment by DanWahlin** [comment]
No need to open another issue. The other one still works. Please use that for comments.
